v0.8.3

diff --git a/.github/workflows/update_version_badge.yml b/.github/workflows/update_version_badge.yml
--- a/.github/workflows/update_version_badge.yml
+++ b/.github/workflows/update_version_badge.yml
@@ -23,25 +23,25 @@ jobs:
           sed -i "s/version='[0-999]*\.[0-9999]*\.[0-999]*'/version='${{ env.VERSION }}'/" setup.py
 
       - name: Print badge line
-        run: grep 'https://img.shields.io/badge/Version' README.md || echo "Badge not found"
+        run: grep 'https://img.shields.io/badge/Version' docs/README.md || echo "Badge not found"
         
       - name: Normalize line endings
-        run: sed -i 's/\r//' README.md
+        run: sed -i 's/\r//' docs/README.md
       
       - name: Update README.md
         run: |
-          sed -i 's|https://img.shields.io/badge/Version-[^)-]*-blue|https://img.shields.io/badge/Version-${{ env.VERSION }}-blue|g' README.md
+          sed -i 's|https://img.shields.io/badge/Version-[^)-]*-blue|https://img.shields.io/badge/Version-${{ env.VERSION }}-blue|g' docs/README.md
 
       - name: Print README.md after update
-        run: cat README.md
+        run: cat docs/README.md
         
       - name: Check for changes
-        run: git diff README.md || echo "No differences detected"
+        run: git diff docs/README.md || echo "No differences detected"
       
       - name: Commit changes
         run: |
           git config --local user.email "ckyb63@gmail.com"
           git config --local user.name "ckyb63"
-          git add README.md setup.py  # Add setup.py to the commit
-          git commit -m "Update version to ${{ env.VERSION }}" || echo "No changes to commit" 
+          git add docs/README.md setup.py  # Add setup.py to the commit
+          git commit -m "Update ${{ env.VERSION }}" || echo "No changes to commit" 
           git push
